In [142]:
from keras.models import Sequential
from keras.layers import Dense,Conv2D,MaxPooling2D,Dropout,Activation,Input,Flatten
from keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import layers
import random

In [3]:
import pandas as pd
import numpy as np

In [197]:
parameters = pd.read_csv('ParametersDataset.csv')
pattern = pd.read_csv('PatternDataset.csv')

In [198]:
parameters

Column1       Column2       Column3       Column4       Column5  \
0  3.000000e-01  3.000000e-01  3.000000e-01  3.000000e-01  3.000000e-01   
1  1.500000e-01  1.500000e-01  1.500000e-01  1.500000e-01  1.500000e-01   
2  3.000000e-02  3.000000e-02  3.000000e-02  3.093700e-02  3.093700e-02   
3  2.000000e+09  2.012500e+09  2.025000e+09  2.000000e+09  2.012500e+09   

        Column6       Column7       Column8       Column9      Column10  ...  \
0  3.000000e-01  3.000000e-01  3.000000e-01  3.000000e-01  3.000000e-01  ...   
1  1.500000e-01  1.500000e-01  1.500000e-01  1.500000e-01  1.546870e-01  ...   
2  3.093700e-02  3.187500e-02  3.187500e-02  3.187500e-02  3.000000e-02  ...   
3  2.025000e+09  2.000000e+09  2.012500e+09  2.025000e+09  2.000000e+09  ...   

    Column72.15   Column73.15   Column74.15   Column75.15   Column76.15  \
0  5.000000e-01  5.000000e-01  5.000000e-01  5.000000e-01  5.000000e-01   
1  2.956250e-01  3.000000e-01  3.000000e-01  3.000000e-01  3.000000e-01   
2  6.000000e-02  5.812500e-02  5.812500e-02  5.812500e-02  5.906200e-02   
3  2.400000e+09  2.375000e+09  2.387500e+09  2.400000e+09  2.375000e+09   

    Column77.15   Column78.15   Column79.15   Column80.15   Column81.15  
0  5.000000e-01  5.000000e-01  5.000000e-01  5.000000e-01  5.000000e-01  
1  3.000000e-01  3.000000e-01  3.000000e-01  3.000000e-01  3.000000e-01  
2  5.906200e-02  5.906200e-02  6.000000e-02  6.000000e-02  6.000000e-02  
3  2.387500e+09  2.400000e+09  2.375000e+09  2.387500e+09  2.400000e+09  

[4 rows x 1296 columns]

In [199]:
pattern

Column1    Column2    Column3    Column4    Column5    Column6  \
0   -2.851472  -2.833037  -2.818918  -2.810664  -2.793551  -2.780483   
1   -3.675394  -3.700862  -3.722869  -3.633762  -3.660300  -3.683143   
2   -4.133559  -4.225237  -4.304977  -4.089050  -4.181504  -4.261840   
3   -4.001553  -4.160083  -4.302769  -3.954363  -4.113038  -4.255730   
4   -3.418395  -3.610925  -3.789871  -3.371578  -3.563475  -3.741626   
5   -2.855638  -3.045657  -3.227272  -2.812821  -3.001608  -3.181787   
6   -2.815344  -2.981247  -3.144803  -2.779561  -2.943831  -3.105525   
7   -3.754727  -3.882525  -4.014743  -3.729380  -3.855178  -3.985188   
8   -6.212861  -6.277389  -6.353945  -6.203676  -6.265509  -6.339253   
9  -10.506419 -10.444755 -10.394215 -10.513453 -10.447420 -10.392573   
10 -11.268599 -11.304992 -11.302145 -11.217389 -11.252531 -11.248435   
11  -7.878341  -8.053199  -8.203067  -7.820728  -7.994108  -8.142525   
12  -6.944567  -7.152592  -7.354733  -6.900922  -7.107514  -7.308152   
13  -9.297998  -9.515399  -9.743719  -9.269764  -9.485575  -9.712205   
14 -16.623355 -16.525053 -16.437529 -16.584313 -16.479385 -16.384950   
15 -13.681424 -13.590283 -13.450135 -13.588400 -13.496589 -13.355724   
16  -9.059088  -9.264255  -9.437534  -9.006876  -9.210864  -9.382788   
17  -9.137723  -9.519813  -9.884745  -9.106145  -9.488239  -9.853152   
18 -14.332212 -15.035490 -15.709776 -14.326156 -15.031493 -15.708100   
19 -23.805595 -21.737079 -20.171297 -23.616941 -21.576264 -20.027619   
20 -10.748482 -10.646135 -10.558602 -10.704394 -10.598742 -10.507795   
21  -7.279456  -7.496566  -7.730213  -7.259936  -7.475628  -7.707593   
22  -6.908404  -7.370568  -7.866349  -6.910506  -7.373965  -7.871127   
23  -8.945689  -9.756781 -10.642484  -8.980840  -9.799738 -10.695066   
24 -14.541197 -16.244383 -18.117461 -14.667678 -16.414108 -18.345285   
25 -31.873764 -23.867896 -19.782232 -31.422441 -23.577731 -19.572656   
26 -13.346326 -12.124279 -11.058696 -13.192297 -11.989650 -10.937921   
27  -8.174431  -7.652192  -7.167841  -8.084899  -7.567184  -7.086452   
28  -5.425264  -5.175612  -4.941826  -5.361538  -5.113723  -4.881369   
29  -3.713270  -3.612595  -3.520519  -3.664054  -3.564704  -3.473649   
30  -2.564871  -2.555502  -2.550790  -2.524660  -2.516835  -2.513387   
31  -1.780032  -1.826877  -1.874938  -1.744893  -1.793907  -1.843865   
32  -1.290364  -1.368462  -1.444124  -1.256249  -1.337522  -1.416097   
33  -1.112153  -1.201395  -1.284416  -1.073388  -1.167310  -1.254779   
34  -1.333516  -1.413996  -1.484793  -1.280341  -1.367776  -1.445371   
35  -2.136654  -2.180924  -2.213073  -2.049819  -2.104796  -2.147604   
36  -3.903414  -3.858033  -3.800533  -3.737848  -3.711031  -3.672017   
37  -7.651617  -7.367116  -7.080065  -7.254213  -7.016680  -6.774336   
38 -17.598619 -16.597389 -15.489848 -15.725261 -14.994082 -14.174624   
39  -9.715043 -11.033405 -12.557024 -10.110304 -11.424263 -12.929559   
40  -2.502027  -3.196419  -3.930763  -2.799434  -3.503156  -4.247772   
41   1.126666   0.651259   0.166524   0.910374   0.430783  -0.058160   
42   2.844269   2.507500   2.175130   2.679566   2.340973   2.006969   
43   2.990787   2.778948   2.580453   2.863803   2.651035   2.451798   
44   1.555961   1.500155   1.461328   1.458754   1.401360   1.361075   
45  -1.142109  -0.978947  -0.814178  -1.232682  -1.072837  -0.911141   
46  -1.748770  -1.650504  -1.554939  -1.901160  -1.801684  -1.705395   
47   1.061232   0.912618   0.767608   0.897814   0.750014   0.605583   
48   3.280069   3.077135   2.880825   3.136070   2.934603   2.739772   
49   4.259396   4.076205   3.904883   4.136872   3.956387   3.787837   
50   4.331217   4.203085   4.090489   4.235580   4.111264   4.002366   
51   3.865379   3.817737   3.784392   3.806084   3.762399   3.732549   
52   3.179532   3.219823   3.266784   3.162985   3.205519   3.254082   
53   2.476620   2.584674   2.688716   2.498449   2.605729   2.708592   
54   1.816333   1.955186   2.081706   1.862614

In [200]:
parameters.iloc[3] = parameters.iloc[3]/1e8
X = pattern.to_numpy().T
y = parameters.to_numpy().T
y[0]

array([ 0.3 ,  0.15,  0.03, 20.  ])

In [201]:
X[0]

array([ -2.851472,  -3.675394,  -4.133559,  -4.001553,  -3.418395,
        -2.855638,  -2.815344,  -3.754727,  -6.212861, -10.506419,
       -11.268599,  -7.878341,  -6.944567,  -9.297998, -16.623355,
       -13.681424,  -9.059088,  -9.137723, -14.332212, -23.805595,
       -10.748482,  -7.279456,  -6.908404,  -8.945689, -14.541197,
       -31.873764, -13.346326,  -8.174431,  -5.425264,  -3.71327 ,
        -2.564871,  -1.780032,  -1.290364,  -1.112153,  -1.333516,
        -2.136654,  -3.903414,  -7.651617, -17.598619,  -9.715043,
        -2.502027,   1.126666,   2.844269,   2.990787,   1.555961,
        -1.142109,  -1.74877 ,   1.061232,   3.280069,   4.259396,
         4.331217,   3.865379,   3.179532,   2.47662 ,   1.816333,
         1.171002,   0.498025,  -0.232852,  -1.040325,  -1.926889])

In [215]:
train_idx = np.random.randint(1296, size=1290)
test_idx = np.random.randint(1296, size=6)

X_train = X[train_idx,:]
y_train = y[train_idx,:]
X_test = X[test_idx,:]
y_test = y[test_idx,:]
X_test
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((1290, 60), (1290, 4), (6, 60), (6, 4))

In [216]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential()
model.add(layers.Dense(64, activation='relu', input_shape=(60,)))
model.add(layers.Dense(256, activation='relu'))
model.add(Dropout(0.25))
model.add(layers.Dense(256, activation='relu'))
model.add(Dropout(0.25))
model.add(layers.Dense(128, activation='relu'))
model.add(Dropout(0.25))
model.add(layers.Dense(128, activation='relu'))
model.add(Dropout(0.25))
model.add(layers.Dense(16, activation='relu'))
model.add(layers.Dense(4))
optimizer = Adam(lr=0.005)
model.compile(optimizer=optimizer, loss='mean_squared_error')

In [217]:
model.fit(X_train, y_train, epochs=200, batch_size=64, verbose=1)

Epoch 1/200
21/21 [==============================] - 1s 8ms/step - loss: 17.5651
Epoch 2/200
21/21 [==============================] - 0s 7ms/step - loss: 5.7040
Epoch 3/200
21/21 [==============================] - 0s 9ms/step - loss: 4.7830
Epoch 4/200
21/21 [==============================] - 0s 8ms/step - loss: 4.0450
Epoch 5/200
21/21 [==============================] - 0s 11ms/step - loss: 3.9064
Epoch 6/200
21/21 [==============================] - 0s 12ms/step - loss: 4.0281
Epoch 7/200
21/21 [==============================] - 0s 13ms/step - loss: 3.1371
Epoch 8/200
21/21 [==============================] - 0s 13ms/step - loss: 2.6684
Epoch 9/200
21/21 [==============================] - 0s 13ms/step - loss: 3.8338
Epoch 10/200
21/21 [==============================] - 0s 12ms/step - loss: 3.8981
Epoch 11/200
21/21 [==============================] - 0s 12ms/step - loss: 2.5047
Epoch 12/200
21/21 [==============================] - 0s 13ms/step - loss: 2.0840
Epoch 13/200
21/21 [========

In [218]:
y_pred = model.predict(X_test)
y_pred

1/1 [==============================] - 0s 116ms/step


array([[ 0.4267951 ,  0.24109367,  0.05186379, 22.80456   ],
       [ 0.46956602,  0.27102467,  0.05491298, 23.542824  ],
       [ 0.33851427,  0.17129165,  0.03029491, 20.821371  ],
       [ 0.33394715,  0.15886563,  0.03298518, 20.515186  ],
       [ 0.33708516,  0.16705135,  0.0295681 , 20.743458  ],
       [ 0.33793047,  0.16802919,  0.02939084, 20.752104  ]],
      dtype=float32)

In [219]:
y_test

array([[ 0.425   ,  0.253125,  0.050625, 22.5     ],
       [ 0.46875 ,  0.276562,  0.054375, 23.25    ],
       [ 0.3375  ,  0.178125,  0.035625, 20.75    ],
       [ 0.30625 ,  0.159375,  0.031875, 20.25    ],
       [ 0.33125 ,  0.16875 ,  0.03375 , 20.75    ],
       [ 0.325   ,  0.178125,  0.034687, 20.75    ]])